########################################################
## !!! WARNING !!! ATENCION !!!                       ##
## Application Properties Basic Configuration         ##
## author: Oscar Rodriguez <oorodriguezc@gmail.com>   ##
##                                                    ##
## MODIFY THIS FILE UNDER YOUR RESPONSIBILITY         ##
## MODIFIQUE ESTE ARCHIVO BAJO SU RESPONSABILIDAD     ##
########################################################
spring:
  profiles:
    active: dev
  application:
    name: Insoftar Backend
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
    open-in-view: false
  jackson:
    locale: es_CO
    time-zone: America/Bogota
  web:
    locale: es_CO
server:
  error:
    include-stacktrace: on_trace_param
insoftar:
  app:
    poweredby: Insoftar S.A.S.
    version: 0.1.0-alpha