########################################################
## !!! WARNING !!! ATENCION !!!                       ##
## Application Properties Basic Configuration         ##
## author: Oscar Rodriguez <oorodriguezc@gmail.com>   ##
##                                                    ##
## MODIFY THIS FILE UNDER YOUR RESPONSIBILITY         ##
## MODIFIQUE ESTE ARCHIVO BAJO SU RESPONSABILIDAD     ##
########################################################
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
logging:
  level:
    org.springframework.web: debug
    org.hibernate.SQL: debug
  file:
    name: logs/insoftar-application-dev.log
  logback:
    rollingpolicy:
      max-file-size: 10MB