spring:
  application:
    name: Insoftar Backend
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/insoftar?serverTimezone=America/Bogota
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    locale: es_CO
    time-zone: America/Bogota
  web:
    locale: es_CO
server:
  error:
    include-stacktrace: on_trace_param
insoftar:
  app:
    poweredby: Insoftar S.A.S.
    version: 0.1.0-alpha